steps:
  - name: gcr.io/cloud-builders/docker
    timeout: 3600s
    args:
      - build
      - -f
      - Dockerfile.thermompnn
      - -t
      - us-central1-docker.pkg.dev/build-wgemini26sfo-2005/gpcrclaw/thermompnn-worker:latest
      - .
images:
  - us-central1-docker.pkg.dev/build-wgemini26sfo-2005/gpcrclaw/thermompnn-worker:latest
timeout: 3600s
